version: "3.1"
services:
  app-pm2:
    container_name: app-pm2
    build: ./blogsever
    volumes:
      - ./blogsever:/usr/src/app 
    ports:
      - 3003:3003
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/cert
      - ./build:/var/www/html/
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass smz8023XXJ
    ports:
      - 6379:6379
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "smz8023XXJ"
      MYSQL_USER: "test"
      MYSQL_PASS: "smz8023smz"
    image: "docker.io/mysql:latest"
    restart: always
    volumes:
      - "./conf/my.cnf:/etc/my.cnf"
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    ports:
      - "3306:3306"
