FROM keymetrics/pm2:latest-alpine
WORKDIR /usr/src/app
# RUN npm config set registry https://registry.npm.taobao.org
# RUN npm i
RUN npm i
EXPOSE 3003
#pm2在docker中使用命令为pm2-docker
# CMD ["pm2-runtime", "start", "--json", "process.json"]
CMD ["pm2-docker", "start", "--json", "process.json"]

